In [2]:
!pip install pandas seaborn

Collecting pandas
  Using cached pandas-2.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.9/294.9 kB 3.3 MB/s eta 0:00:00a 0:00:01
Collecting pytz>=2020.1
  Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 508.0/508.0 kB 6.2 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: python-dateutil>=2.8.2 in /home/predator/.pyenv/versions/3.10.14/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Collecting numpy>=1.22.4
  Downloading numpy-2.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 5.0 MB/s eta 0:00:0000:0100:01
Collecting tzdata>=2022.7
  Downloading tzdata-2025.1-py2.py3-none-any.whl (346 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 346.8/346.8 kB 6.5 MB/s eta 0:00:0000:01
Collecting matplotlib!=3.6.1,>=3.4
  Using cached matplotlib-3.10.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.6 MB)
Collecting fonttools>=4.22.0
  Downloading fonttools-4.55.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 7.3 MB/s eta 0:00:00:00:0100:01
Collecting contourpy>=1.0.1
  Downloading contourpy-1.3.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (324 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 325.0/325.0 kB 5.5 MB/s eta 0:00:0000:01
Collecting pyparsing>=2.3.1
  Downloading pyparsing-3.2.1-py3-none-any.whl (107 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.7/107.7 kB 2.7 MB/s eta 0:00:00a 0:00:01
Collecting pillow>=8
  Downloading pillow-11.1.0-cp310-cp310-manylinux_2_28_x86_64.whl (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 4.3 MB/s eta 0:00:00:00:0100:01
Collecting cycler>=0.10
  Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Collecting kiwisolver>=1.3.1
  Downloading kiwisolver-1.4.8-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 7.7 MB/s eta 0:00:00:00:0100:01
Requirement already satisfied: packaging>=20.0 in /home/predator/.pyenv/versions/3.10.14/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.2)
Requirement already satisfied: six>=1.5 in /home/predator/.pyenv/versions/3.10.14/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Installing collected packages: pytz, tzdata, pyparsing, pillow, numpy, kiwisolver, fonttools, cycler, pandas, contourpy, matplotlib, seaborn
Successfully installed contourpy-1.3.1 cycler-0.12.1 fonttools-4.55.5 kiwisolver-1.4.8 matplotlib-3.10.0 numpy-2.2.2 pandas-2.2.3 pillow-11.1.0 pyparsing-3.2.1 pytz-2024.2 seaborn-0.13.2 tzdata-2025.1

[notice] A new release of pip is available: 23.0.1 -> 24.3.1
[notice] To update, run: pip install --upgrade pip

In [3]:
import pandas as pd
import seaborn as sns 
penguins = sns.load_dataset('penguins')
penguins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [4]:
# slicing
penguins.loc[302:343,'species':'bill_depth_mm']

    species  island  bill_length_mm  bill_depth_mm
302  Gentoo  Biscoe            47.4           14.6
303  Gentoo  Biscoe            50.0           15.9
304  Gentoo  Biscoe            44.9           13.8
305  Gentoo  Biscoe            50.8           17.3
306  Gentoo  Biscoe            43.4           14.4
307  Gentoo  Biscoe            51.3           14.2
308  Gentoo  Biscoe            47.5           14.0
309  Gentoo  Biscoe            52.1           17.0
310  Gentoo  Biscoe            47.5           15.0
311  Gentoo  Biscoe            52.2           17.1
312  Gentoo  Biscoe            45.5           14.5
313  Gentoo  Biscoe            49.5           16.1
314  Gentoo  Biscoe            44.5           14.7
315  Gentoo  Biscoe            50.8           15.7
316  Gentoo  Biscoe            49.4           15.8
317  Gentoo  Biscoe            46.9           14.6
318  Gentoo  Biscoe            48.4           14.4
319  Gentoo  Biscoe            51.1           16.5
320  Gentoo  Biscoe            48.5           15.0
321  Gentoo  Biscoe            55.9           17.0
322  Gentoo  Biscoe            47.2           15.5
323  Gentoo  Biscoe            49.1           15.0
324  Gentoo  Biscoe            47.3           13.8
325  Gentoo  Biscoe            46.8           16.1
326  Gentoo  Biscoe            41.7           14.7
327  Gentoo  Biscoe            53.4           15.8
328  Gentoo  Biscoe            43.3           14.0
329  Gentoo  Biscoe            48.1           15.1
330  Gentoo  Biscoe            50.5           15.2
331  Gentoo  Biscoe            49.8           15.9
332  Gentoo  Biscoe            43.5           15.2
333  Gentoo  Biscoe            51.5           16.3
334  Gentoo  Biscoe            46.2           14.1
335  Gentoo  Biscoe            55.1           16.0
336  Gentoo  Biscoe            44.5           15.7
337  Gentoo  Biscoe            48.8           16.2
338  Gentoo  Biscoe            47.2           13.7
339  Gentoo  Biscoe             NaN            NaN
340  Gentoo  Biscoe            46.8           14.3
341  Gentoo  Biscoe            50.4           15.7
342  Gentoo  Biscoe            45.2           14.8
343  Gentoo  Biscoe            49.9           16.1

In [7]:
# displays the dataframe with correct formatting
display(penguins)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

The DataFrame.copy() method in pandas is used in several important scenarios to ensure data integrity and prevent unintended modifications to your original data. Here are the key situations when you should use DataFrame.copy():
Data Manipulation Safety
Preserving Original Data
When you need to perform operations on a DataFrame without altering the original, using copy() is crucial. This allows you to experiment with data transformations while keeping the source data intact14.
Avoiding Side Effects
In data analysis workflows, it's common to create multiple versions of a DataFrame. Using copy() prevents accidental changes to shared data, especially when working with large datasets or in complex analysis pipelines37.
Memory Management
Deep vs. Shallow Copy
By default, copy() creates a deep copy, duplicating both the structure and the data. This is useful when you need a completely independent copy. However, for memory efficiency, you can use a shallow copy with copy(deep=False) when you only need to modify the DataFrame structure26.
Multithreading Considerations
When working in multithreaded environments, using copy() can help avoid race conditions and ensure thread safety, as pandas is not inherently thread-safe6.
Best Practices
Always use deep copy unless you specifically need a shallow copy for memory concerns or particular functionality3.
Confirm the type of copy needed based on your data manipulation tasks3.
Be aware of nested objects: When copying DataFrames with Python objects, note that a deep copy will not recursively copy nested object data6.
New Behavior in Pandas 3.0
Starting from Pandas 3.0, shallow copies behave differently due to a new lazy copy mechanism (copy-on-write):
Even with deep=False, changes to either the original or the copy will not affect the other4.
This behavior can be enabled in earlier versions by setting pd.options.mode.copy_on_write = True46.
In conclusion, using DataFrame.copy() is a crucial practice in pandas for maintaining data integrity, especially when you need to preserve the original data while performing transformations or when working with complex data analysis pipelines. Always consider the specific requirements of your task and the potential impact on memory usage when deciding between deep and shallow copies.